/* ============================================================================
 *  游医天下 · 3D 版数据层
 *  九境 / 五脏五色 / 世界模型 / GNPC 绑定 / visvise 资产规格
 *  内容为虚构，如有雷同纯属巧合。
 * ==========================================================================*/
const ORGANS = {
  gan:  { key:'gan',  zang:'肝', color:'青', element:'木', hex:'#2f8f86', desc:'青属木，主疏泄，藏魂。' },
  xin:  { key:'xin',  zang:'心', color:'赤', element:'火', hex:'#c0392b', desc:'赤属火，主血脉，藏神。' },
  pi:   { key:'pi',   zang:'脾', color:'黄', element:'土', hex:'#caa12f', desc:'黄属土，主运化，藏意。' },
  fei:  { key:'fei',  zang:'肺', color:'白', element:'金', hex:'#e9e9e2', desc:'白属金，主气司呼吸，藏魄。' },
  shen: { key:'shen', zang:'肾', color:'黑', element:'水', hex:'#2b2b33', desc:'黑属水，主封藏，藏志。' },
};
const ORGAN_ORDER = ['gan','xin','pi','fei','shen'];

const WORLD_MODEL = {
  gan:  { env:'青气漫野，疏木成林，檐角挑出竹影三两。', dress:'青布直裰，腰束墨绿绦带，木簪。', tint:'#2f8f86' },
  xin:  { env:'赤霞斜照，庭中红枫点染，灯影摇红。',     dress:'赤缘交领，披茜色半臂，腕悬朱珠。', tint:'#c0392b' },
  pi:   { env:'黄土夯墙，谷场铺金，远山如熟麦垂垂。',   dress:'黄绢短褐，系土黄围裙，麻履。',     tint:'#caa12f' },
  fei:  { env:'素白雾霭铺开，石阶沁凉，月色如霜。',     dress:'白衣如雪，外罩素绢大袖，银簪。',   tint:'#cfd2d6' },
  shen: { env:'玄水绕屋，墨色山影沉入夜，瓦上凝露。',   dress:'玄色深衣，黑貂镶边，佩乌玉。',     tint:'#2b2b33' },
};

/* gnpcKey 对应 gnpc_config.json 中的 npc 条目 */
const LOCATIONS = [
  {
    id:'shijing', name:'市井流落', subtitle:'其一 · 疫病初起的街巷',
    mapPos:{x:14,y:78}, motif:'market', gnpcKey:'shijing',
    sceneModel:'models/shijing_scene.glb', charModel:'models/shijing_char.glb',
    bg:'assets/bgs/国风游戏场景背景图_白描水墨灰调_低多边形可转3D_明清南方_2026-09-11T04-45-01.png',
    char:'assets/chars/国风游戏人物设定图_全身立绘_白描水墨线稿风格_素白背景_明_2026-09-11T04-43-55.png',
    intro:['明亡清立之际，时疫顺着运河一路北上。\n张天一背着药囊，初入这座南方的市井。',
           '青石板缝隙渗着污水，檐下挤满面色青白、咳声连片的流民。\n一个枯瘦老者蜷在墙根，指节发乌。'],
    npc:{ name:'流民·周阿公', role:'街口乞食的老卒', baZi:'庚午 丁亥 甲子 癸酉', desc:'年迈体衰，寒邪束表，中气下陷。' },
    jingFang:{ name:'桂枝汤合参苓白术意', note:'辛温解表、培土生金，以复营卫。' },
    puzzle:{ hint:'老者面色青白、手足不温，寒邪伤肺（白）而脾虚（黄）不运。\n经方重在温卫与健脾。',
             suggested:{gan:20,xin:25,pi:70,fei:75,shen:30} },
    outcomes:{ shang:{line:'一剂下去，周阿公额上沁出微汗，青白之色转润。'}, zhong:{line:'三日咳减，气力却未复。'}, xia:{line:'药不对症，寒邪内陷，幸得姜汤回气。'} },
    asset:{ scene:'白描风格的南方市井街口：青石板路、两侧斜檐木棚、竹筐与药釜剪影，枯笔山墙，雾气，单色水墨灰调，低多边形可转 glTF。',
            char:'枯瘦老者，青布短褐、束腰，蜷坐墙根，指节发乌，白描墨线低多边形角色，可绑定 GNPC 对话。' },
  },
  {
    id:'bianjing', name:'边境解围', subtitle:'其二 · 关隘风雪中的伤卒',
    mapPos:{x:26,y:56}, motif:'border', gnpcKey:'bianjing',
    sceneModel:'models/bianjing_scene.glb', charModel:'models/bianjing_char.glb',
    bg:'assets/bgs/国风游戏场景背景图_白描水墨枯笔墨调_低多边形可转3D_明清_2026-09-11T04-44-59.png',
    char:'assets/chars/国风游戏人物设定图_全身立绘_白描水墨线稿风格_素白背景_明_2026-09-11T04-43-57.png',
    intro:['张天一循逃难队伍往北，被卷进风雪关隘。\n边军刚退流寇，伤者塞途。',
           '一名戍卒被乱箭划破甲胄，血瘀胁下，又染风寒，面赤唇紫，喘促不止。'],
    npc:{ name:'戍卒·马三', role:'守关的弓手', baZi:'戊辰 甲子 丙戌 庚寅', desc:'外伤血瘀（肝），复感风热（心），表里同病。' },
    jingFang:{ name:'血府逐瘀意合银翘', note:'活血行气以疏肝，轻清透热以宁心。' },
    puzzle:{ hint:'胁下瘀痛属肝（青），面赤喘促属心（赤）有热。\n经方以疏肝活血为主，佐以清心。',
             suggested:{gan:80,xin:60,pi:30,fei:40,shen:25} },
    outcomes:{ shang:{line:'瘀血得行，马三胁下松开，吐出一口瘀血腥气。'}, zhong:{line:'痛势减半，伤口仍红肿。'}, xia:{line:'瘀不去而热反盛，高热谵语，幸得针法稳住。'} },
    asset:{ scene:'风雪关隘：夯土木门、旗杆、远山雪岭、积雪地面，白描枯笔墨调，低多边形场景。',
            char:'披甲戍卒，扶矛而立，胁下裹伤，面赤唇紫，低多边形白描角色，可绑定 GNPC。' },
  },
  {
    id:'fuyao', name:'府衙转运', subtitle:'其三 · 案牍劳形的师爷',
    mapPos:{x:38,y:70}, motif:'yamen', gnpcKey:'fuyao',
    sceneModel:'models/fuyao_scene.glb', charModel:'models/fuyao_char.glb',
    bg:'assets/bgs/国风游戏场景背景图_白描水墨墨线_低多边形可转3D_清代府衙_2026-09-11T04-45-01.png',
    char:'assets/chars/国风游戏人物设定图_全身立绘_白描水墨线稿风格_素白背景_清_2026-09-11T04-44-20.png',
    intro:['疫中衙门忙着转运赈粮，张天一受邀入府。\n书房烛火通明，师爷已三日未眠。',
           '那人两颧绯红、舌尖绛而少津，腰背酸软，笔下却仍旧飞快——\n劳心竭肾。'],
    npc:{ name:'师爷·柳明之', role:'管粮赈的幕友', baZi:'壬申 辛亥 丁卯 甲辰', desc:'心火亢于上（赤），肾水亏于下（黑），水火失济。' },
    jingFang:{ name:'天王补心合六味意', note:'上清心火、下滋肾水，引火归元。' },
    puzzle:{ hint:'舌红颧赤为心（赤）火旺，腰酸神疲为肾（黑）亏。\n经方须上清下补，不可独泻。',
             suggested:{gan:30,xin:70,pi:45,fei:35,shen:80} },
    outcomes:{ shang:{line:'一宿安眠，柳明之神清，案上赈册一日厘清。'}, zhong:{line:'火略敛而神未充，午后便觉眼皮千斤。'}, xia:{line:'清泻太过，反泄泻畏寒，肾阳更伤。'} },
    asset:{ scene:'清代府衙书房：公案、博古架、烛台、窗外活水莲池，白描墨线，低多边形室内。',
            char:'着青绸直裰的师爷，伏案执笔，两颧绯红，低多边形白描角色，可绑定 GNPC。' },
  },
  {
    id:'biyu', name:'婢女园林', subtitle:'其四 · 深宅里的郁郁之人',
    mapPos:{x:50,y:52}, motif:'garden', gnpcKey:'biyu',
    sceneModel:'models/biyu_scene.glb', charModel:'models/biyu_char.glb',
    bg:'assets/bgs/国风游戏场景背景图_白描枯笔_低多边形可转3D_江南盐商园林_2026-09-11T04-45-05.png',
    char:'assets/chars/国风游戏人物设定图_全身立绘_白描水墨线稿风格_素白背景_清_2026-09-11T04-44-23.png',
    intro:['一处盐商园林邀张天一诊脉。\n假山曲水之间，一名婢女低眉而立，脉弦而细。',
           '她入府三年，思虑不舒，茶饭渐减，月事愆期——\n郁出来的病。'],
    npc:{ name:'婢女·素娘', role:'园中侍弄花木的婢', baZi:'乙酉 己卯 壬午 辛丑', desc:'肝郁（青）乘脾（黄），气滞而血虚。' },
    jingFang:{ name:'逍遥散意', note:'疏肝解郁、健脾养血，使木土相安。' },
    puzzle:{ hint:'胸闷叹气、脉弦属肝（青）郁；纳差乏力属脾（黄）弱。\n经方以疏肝为先，兼顾健脾。',
             suggested:{gan:75,xin:35,pi:65,fei:30,shen:30} },
    outcomes:{ shang:{line:'素娘眉间松动，隔着花墙轻轻哼起小调。'}, zhong:{line:'嗳气稍减，情怀仍郁，肯多吃半碗饭。'}, xia:{line:'疏肝过峻，反觉心慌头晕，郁结未开。'} },
    asset:{ scene:'江南盐商园林：太湖石假山、曲水、芍药架、廊榭，白描枯笔，低多边形园林。',
            char:'低眉婢女，束腰绢裙、钗环，立于花墙下，低多边形白描角色，可绑定 GNPC。' },
  },
  {
    id:'dangzhou', name:'荡舟湖心', subtitle:'其五 · 烟波上的渔家女',
    mapPos:{x:62,y:66}, motif:'lake', gnpcKey:'dangzhou',
    sceneModel:'models/dangzhou_scene.glb', charModel:'models/dangzhou_char.glb',
    bg:'assets/bgs/国风游戏场景背景图_白描水墨灰蓝调_低多边形可转3D_烟波湖_2026-09-11T04-45-03.png',
    char:'assets/chars/国风游戏人物设定图_全身立绘_白描水墨线稿风格_素白背景_清_2026-09-11T04-44-24.png',
    intro:['张天一搭一叶扁舟过湖。\n舟女赤足摇橹，身形困重、头目昏蒙，舌苔白腻如敷粉。',
           '她说连月阴雨，舱里潮得能拧出水，一家老小都提不起精神。'],
    npc:{ name:'渔女·阿菱', role:'湖上讨生活的舟家', baZi:'己巳 癸酉 戊辰 壬子', desc:'湿困脾（黄）肺（白），气化不行，清阳不升。' },
    jingFang:{ name:'五苓散合藿香正气意', note:'化气利水、芳香化湿，醒脾宣肺。' },
    puzzle:{ hint:'身重苔腻为湿困脾（黄），胸闷为肺（白）气不宣。\n经方重在化湿醒脾、宣肺利水。',
             suggested:{gan:30,xin:25,pi:80,fei:65,shen:35} },
    outcomes:{ shang:{line:'一服微汗，阿菱如卸千钧，橹声都轻快了。'}, zhong:{line:'困重稍减，头仍微昏。'}, xia:{line:'利水伤阴，反口干唇燥，湿未去而津已伤。'} },
    asset:{ scene:'烟波湖泊：扁舟、芦苇、远岸炊烟、雾霭，白描水墨灰蓝调，低多边形水面。',
            char:'赤足摇橹的渔家女，短衫绲边，立于舟中，低多边形白描角色，可绑定 GNPC。' },
  },
  {
    id:'cunliu', name:'村民留宿', subtitle:'其六 · 瘟疫中的山村民舍',
    mapPos:{x:68,y:50}, motif:'village', gnpcKey:'cunliu',
    sceneModel:'models/cunliu_scene.glb', charModel:'models/cunliu_char.glb',
    bg:'assets/bgs/国风游戏场景背景图_白描枯笔夜色_低多边形可转3D_山村民舍_2026-09-11T04-45-06.png',
    char:'assets/chars/国风游戏人物设定图_全身立绘_白描水墨线稿风格_素白背景_山_2026-09-11T04-44-26.png',
    intro:['夜半投宿山村，正撞上一户疫病。\n灶膛冷着，村妪高热喘促，脉细数如缕。',
           '她说村里已没了郎中，年轻人都逃了，只剩她守着发烫的小孙儿。'],
    npc:{ name:'村妪·王婆', role:'守着孙儿的老人', baZi:'丙寅 庚子 己未 戊辰', desc:'温邪犯肺（白）化热，久病及肾（黑），正虚邪恋。' },
    jingFang:{ name:'白虎合生脉意', note:'清肺泄热以救津，益气固肾以防脱。' },
    puzzle:{ hint:'高热喘促为肺（白）热伤津，神疲脉弱为肾（黑）气不摄。\n经方须清热生津兼固其本。',
             suggested:{gan:25,xin:40,pi:45,fei:85,shen:70} },
    outcomes:{ shang:{line:'热退身凉，王婆搂着退烧的孙儿老泪纵横。'}, zhong:{line:'热势挫而余热未清，孙儿仍有些嗜睡。'}, xia:{line:'清润失度，泄泻肢冷，邪陷正脱，幸得回阳。'} },
    asset:{ scene:'山村民舍：夯土矮屋、柴垛、灶膛、远山松林、夜色，白描枯笔，低多边形村落。',
            char:'守灶村妪，褐布褙子、挎孙儿，面容憔悴，低多边形白描角色，可绑定 GNPC。' },
  },
  {
    id:'keju', name:'科举揭发', subtitle:'其七 · 贡院里的不眠举子',
    mapPos:{x:76,y:64}, motif:'exam', gnpcKey:'keju',
    sceneModel:'models/keju_scene.glb', charModel:'models/keju_char.glb',
    bg:'assets/bgs/国风游戏场景背景图_白描水墨墨线_低多边形可转3D_清代贡院_2026-09-11T04-45-03.png',
    char:'assets/chars/国风游戏人物设定图_全身立绘_白描水墨线稿风格_素白背景_清_2026-09-11T04-44-32.png',
    intro:['会试之年，张天一入贡院为考生施针。\n一名举子面色苍白、心神不宁，却攥着一卷夹带。',
           '他低声坦白：考官受贿、闱墨有弊。\n话音未落，已冷汗涔涔、心悸怔忡。'],
    npc:{ name:'举子·沈砚', role:'欲揭弊的应试书生', baZi:'甲戌 丁丑 癸酉 乙卯', desc:'心（赤）神不宁、肾（黑）阴亏虚，又兼肝郁（青）化火。' },
    jingFang:{ name:'黄连阿胶合安神意', note:'滋阴降火、交通心肾，先安其神再图其事。' },
    puzzle:{ hint:'心悸失眠为心（赤）肾（黑）不交，郁火为肝（青）。\n经方重在滋阴安神、稍佐疏肝。',
             suggested:{gan:50,xin:70,pi:35,fei:30,shen:80} },
    outcomes:{ shang:{line:'沈砚神定，当庭呈出实证，贡院弊案一朝尽揭。'}, zhong:{line:'神稍安而疑窦未消，终递了状，却迟了一步。'}, xia:{line:'惊则气乱，陡然昏厥，揭弊不了了之。'} },
    asset:{ scene:'清代贡院号舍：号板、灯笼、答卷、高墙夜色，白描墨线，低多边形考场。',
            char:'青衿举子，怀抱夹带、面色苍白，低多边形白描角色，可绑定 GNPC。' },
  },
  {
    id:'huangchao', name:'皇朝震动', subtitle:'其八 · 大疫中的庙堂',
    mapPos:{x:82,y:40}, motif:'palace', gnpcKey:'huangchao',
    sceneModel:'models/huangchao_scene.glb', charModel:'models/huangchao_char.glb',
    bg:'assets/bgs/中国传统风格游戏场景背景图_明清宫殿朝堂大殿内景_庄严空旷的_2026-09-11T08-31-21.png',
    char:'assets/chars/国风游戏人物设定图_全身立绘_白描水墨线稿风格_素白背景_清_2026-09-11T04-44-20.png',
    intro:['弊案牵出疫中贪渎，朝野震动。\n张天一被召入宫，为病倒的辅臣问诊——\n京中已是大疫。',
           '老臣五脏俱损、元气垂竭，脉如游丝。\n一城人的安危，系在这一方脉枕上。'],
    npc:{ name:'辅臣·裴阁老', role:'主持赈疫的柱石之臣', baZi:'辛亥 丙申 戊子 壬子', desc:'久病五脏俱虚，以脾（黄）肾（黑）为本，心肺（白赤）为标。' },
    jingFang:{ name:'参附合生脉意', note:'急救回阳、益气固脱，培土封藏以续命。' },
    puzzle:{ hint:'垂危之际，急则治标、缓则治本。\n经方以固脾肾（黄黑）元气为先，兼顾心肺（白赤）。',
             suggested:{gan:40,xin:55,pi:80,fei:60,shen:85} },
    outcomes:{ shang:{line:'参附一进，裴阁老回阳苏醒，遂颁《避疫十事》于天下。'}, zhong:{line:'命悬一线中稳住，政事移交他人，弊政未全清。'}, xia:{line:'回天乏术，裴阁老溘然长逝，疫势更烈。'} },
    asset:{ scene:'清代宫殿：金柱、宝座、宫灯、宫门，白描枯笔，低多边形殿宇（单色水墨）。',
            char:'紫袍辅臣，扶案而坐、须发皆白，低多边形白描角色，可绑定 GNPC。' },
  },
  {
    id:'xiangye', name:'回归乡野', subtitle:'其九 · 功成身退的归途',
    mapPos:{x:86,y:18}, motif:'country', gnpcKey:'zhangtianyi',
    sceneModel:'models/xiangye_scene.glb', charModel:'models/zhangtianyi_char.glb',
    bg:'assets/bgs/国风游戏场景背景图_白描枯笔田园_低多边形可转3D_乡野归途_2026-09-11T04-45-07.png',
    char:'assets/chars/国风游戏人物设定图_全身立绘_白描水墨线稿风格_素白背景_明_2026-09-11T04-44-33.png',
    intro:['事了拂衣去。\n张天一辞了封赏，背起旧药囊，沿来路往乡野走。',
           '九境走过，市井的咳、关隘的血、园林的郁……都化在这一囊草木里。'],
    npc:{ name:'游医·张天一', role:'归乡的游医', baZi:'行医半生，未立党籍', desc:'五色入五脏，五法归于一心。\n医者意也。' },
    jingFang:{ name:'无方之方', note:'不执一药，不泥一经，随证治之。' },
    puzzle:null,
    outcomes:{ shang:{line:'老柳下歇脚，听见孩童念：“游医张，药囊香。\n”'}, zhong:{line:'沿田埂慢走，把见闻写进磨破的医案。'}, xia:{line:'回望来路，雾里九境皆朦胧，拢了拢药囊。'} },
    asset:{ scene:'乡野归途：老柳、田埂、药棚、淡墨远山，白描枯笔，低多边形田园。',
            char:'布袍游医，背药囊、持杖，低多边形白描角色（主角，非 GNPC 也可对话）。' },
  },
];

/* ============================================================================
 *  用药方案推导
 *  HERBS：每味药归经(五脏权重)、剂量区间(g)、性味；FORMULA_RULES：每境底方与按五脏遴选的候选药
 *  用户拖动五色滑块 → 按数值强弱从候选药中遴选并拟定剂量，得到「具体用药方案」
 * ==========================================================================*/
const HERBS = {
  guizhi:    { name:'桂枝', zang:{gan:1,xin:2},      dose:[6,10],  note:'辛温，温通卫阳' },
  baishao:   { name:'白芍', zang:{gan:2},            dose:[9,15],  note:'酸敛，养血柔肝' },
  shengjiang:{ name:'生姜', zang:{pi:2,fei:1},       dose:[3,6],   note:'辛温，散寒温中' },
  dazao:     { name:'大枣', zang:{pi:2},             dose:[6,12],  note:'甘温，补中养血' },
  gancao:    { name:'甘草', zang:{pi:2,xin:1},       dose:[3,6],   note:'甘平，调和诸药' },
  renshen:   { name:'人参', zang:{pi:2,fei:2,shen:1},dose:[6,10],  note:'大补元气' },
  baizhu:    { name:'白术', zang:{pi:2},             dose:[9,15],  note:'健脾燥湿' },
  fuling:    { name:'茯苓', zang:{pi:1,shen:1},      dose:[10,15], note:'健脾渗湿' },
  huangqi:   { name:'黄芪', zang:{pi:2,fei:2},       dose:[10,20], note:'益气固表' },
  xingren:   { name:'杏仁', zang:{fei:2},            dose:[6,10],  note:'降气止咳' },
  jiegeng:   { name:'桔梗', zang:{fei:2},            dose:[6,10],  note:'宣肺利咽' },
  dangshen:  { name:'党参', zang:{pi:2,fei:2},       dose:[10,15], note:'健脾益气' },
  chaihu:    { name:'柴胡', zang:{gan:2},            dose:[6,10],  note:'疏肝解郁' },
  xiangfu:   { name:'香附', zang:{gan:2},            dose:[6,10],  note:'理气疏肝' },
  danggui:   { name:'当归', zang:{gan:2,xin:1},      dose:[9,15],  note:'补血活血' },
  danshen:   { name:'丹参', zang:{xin:2,gan:1},      dose:[10,15], note:'活血宁心' },
  honghua:   { name:'红花', zang:{gan:2},            dose:[3,6],   note:'活血通经' },
  taoren:    { name:'桃仁', zang:{gan:2},            dose:[6,10],  note:'破血化瘀' },
  huanglian: { name:'黄连', zang:{xin:2},            dose:[3,6],   note:'清心降火' },
  huangqin:  { name:'黄芩', zang:{fei:1,xin:1},      dose:[6,10],  note:'清热泻火' },
  zhizi:     { name:'栀子', zang:{xin:1,shen:1},     dose:[6,10],  note:'泻火除烦' },
  shengdi:   { name:'生地', zang:{shen:2,xin:1},     dose:[10,15], note:'滋阴凉血' },
  shudihuang:{ name:'熟地', zang:{shen:2},           dose:[10,20], note:'滋肾填精' },
  shanzhuyu: { name:'山茱萸',zang:{shen:2},          dose:[6,12],  note:'固肾涩精' },
  zhimu:     { name:'知母', zang:{shen:1,fei:1},     dose:[6,10],  note:'滋阴清热' },
  huangbai:  { name:'黄柏', zang:{shen:1},           dose:[6,10],  note:'泻相火' },
  rougui:    { name:'肉桂', zang:{shen:1,xin:1},     dose:[3,6],   note:'引火归元' },
  fuzi:      { name:'附子', zang:{shen:2,xin:1},     dose:[3,10],  note:'回阳救逆' },
  mahuang:   { name:'麻黄', zang:{fei:2},            dose:[3,6],   note:'发汗解表' },
  huoxiang:  { name:'藿香', zang:{pi:2,fei:1},       dose:[6,10],  note:'芳香化湿' },
  banxia:    { name:'半夏', zang:{pi:2,fei:1},       dose:[6,10],  note:'燥湿化痰' },
  chenpi:    { name:'陈皮', zang:{pi:2},             dose:[6,10],  note:'理气燥湿' },
  maijidong: { name:'麦冬', zang:{fei:1,xin:1},      dose:[9,15],  note:'养阴生津' },
  wuweizi:   { name:'五味子',zang:{fei:2,shen:2},    dose:[3,6],   note:'敛肺固肾' },
  zexie:     { name:'泽泻', zang:{shen:1},           dose:[9,15],  note:'利水渗湿' },
};

const FORMULA_RULES = {
  shijing:  { base:['guizhi','baishao','shengjiang','dazao','gancao'],
              byOrgan:{ pi:['baizhu','fuling','dangshen'], fei:['xingren','jiegeng','huangqi'] } },
  bianjing: { base:['danshen','danggui','chaihu','gancao'],
              byOrgan:{ gan:['honghua','taoren','xiangfu'], xin:['huangqin','huanglian'], fei:['jiegeng'] } },
  fuyao:    { base:['shengdi','shudihuang','danshen','gancao'],
              byOrgan:{ xin:['huanglian','zhizi','maijidong'], shen:['shanzhuyu','zhimu','rougui'], fei:['maijidong'] } },
  biyu:     { base:['chaihu','danggui','baishao','baizhu','gancao'],
              byOrgan:{ gan:['xiangfu','danshen'], pi:['fuling','chenpi','dangshen'] } },
  dangzhou: { base:['huoxiang','banxia','chenpi','fuling','gancao'],
              byOrgan:{ pi:['baizhu','zexie'], fei:['xingren','jiegeng'], shen:['zexie'] } },
  cunliu:   { base:['huangqin','maijidong','wuweizi','gancao'],
              byOrgan:{ fei:['xingren','jiegeng'], shen:['shudihuang','shanzhuyu'], xin:['huanglian'] } },
  keju:     { base:['huanglian','shengdi','danshen','gancao'],
              byOrgan:{ shen:['shudihuang','shanzhuyu','zhimu'], xin:['zhizi','maijidong'], gan:['chaihu','xiangfu'] } },
  huangchao:{ base:['renshen','fuzi','maijidong','wuweizi','gancao'],
              byOrgan:{ pi:['baizhu','fuling','huangqi'], shen:['shudihuang','rougui'], fei:['huangqi'], xin:['danshen'] } },
};

window.YIYI = { ORGANS, ORGAN_ORDER, WORLD_MODEL, LOCATIONS, HERBS, FORMULA_RULES };
